name: Build and Upload
on:
  push:
    branches:
      - master
      - 'release-*'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    paths-ignore:
      - "**.md"
      
jobs:
  build-publish-docker-helm:
    name: Build & Publish Docker Image & Helm Chart
    runs-on: ubuntu-latest
    env:
      HELM_CHART_PATH: package/helm
      TX_TOKEN: ${{ secrets.TX_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Instalar Cliente de Transifex
      run: |
        curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash
        echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configurar Acceso a Transifex
        run: |
          echo "[https://www.transifex.com]" > ~/.transifexrc
          echo "token = ${{ secrets.TX_TOKEN }}" >> ~/.transifexrc
  
      - name: Descargar Traducciones Españolas
        run: |
          tx init --skipsetup
          tx pull -l es  # Asume que 'es' es el código de idioma para español

      - name: Set env.ARTIFACT_VERSION
        run: |
          wget -q https://raw.githubusercontent.com/Bahmni/bahmni-infra-utils/main/setArtifactVersion.sh && chmod +x setArtifactVersion.sh
          ./setArtifactVersion.sh
          echo "ARTIFACT_VERSION=$(cat ARTIFACT_VERSION)" >> $GITHUB_ENV
          rm setArtifactVersion.sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker - Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Docker - Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: package/docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: hcsba/default-config-hcsba-2024:${{ env.ARTIFACT_VERSION }},hcsba/default-config-hcsba-2024:latest

      - name: Update Version and Image Tag in Helm Chart
        run: |
          yq e --inplace '.image.tag = strenv(ARTIFACT_VERSION)' $HELM_CHART_PATH/values.yaml
          yq e --inplace '.version = strenv(ARTIFACT_VERSION)' $HELM_CHART_PATH/Chart.yaml

      - name: Helm Lint
        run: helm lint $HELM_CHART_PATH

      - name: Helm Package
        run: helm package $HELM_CHART_PATH

      - uses: actions/checkout@v2
        with:
          repository: Bahmni/helm-charts
          ref: gh-pages
          path: helm-charts
          persist-credentials: false

      - name: Copy Helm Archive
        run: |
          mkdir -p helm-charts/default-config/ && cp *.tgz helm-charts/default-config/

      - name: Helm Index
        working-directory: helm-charts/
        run: helm repo index --merge index.yaml --url https://bahmni.github.io/helm-charts/ .

      - name: Commit and Push Chart Repository
        working-directory: helm-charts/
        run: |
          git config user.name "${{ secrets.BAHMNI_USERNAME }}"
          git config user.email "${{ secrets.BAHMNI_EMAIL }}"
          git add .
